version: '3.8'

services:
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=B2test
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=jaimeislam
    networks:
      - mynetwork

  app:
    image: codedecode25/dockerdemoapril:0.0.1
    ports:
      - "2000:2000"
    environment:
      - spring.datasource.url=jdbc:postgresql://db:5432/B2test
      - spring.datasource.username=postgres
      - spring.datasource.password=jaimeislam
    depends_on:
      - db
    networks:
      - mynetwork

networks:
  mynetwork:
