version: '3.8'

services:
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=B2_final_touch
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=jaimeislam10
    networks:
      - mynetwork

  app:
    image: javaimage:javaimage1
    ports:
      - "2000:2000"
    environment:
      - spring.datasource.url=jdbc:postgresql://db:5432/B2_final_touch
      - spring.datasource.username=postgres
      - spring.datasource.password=jaimeislam10
    depends_on:
      - db
    networks:
      - mynetwork

networks:
  mynetwork:
