version: '3.8'

services:
  dibi:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=B2Bh
      - POSTGRES_USER=mouade
      - POSTGRES_PASSWORD=mouade
    networks:
      - mynetwork

  chantan:
    image: springboot
    ports:
      - "2000:2000"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://dibi:5432/B2Bh
      - SPRING_DATASOURCE_USERNAME=mouade
      - SPRING_DATASOURCE_PASSWORD=mouade
    depends_on:
      - dibi
    networks:
      - mynetwork

networks:
  mynetwork:
