name: Construction d'un projet

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: B2_final_touch
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: jaimeislam10
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres -d B2_final_touch"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Wait for PostgreSQL to be ready
        run: |
          for i in {1..30}; do
            if pg_isready -h localhost -p 5432 -U postgres; then
              echo "PostgreSQL is ready"
              break
            fi
            echo "Waiting for PostgreSQL to load..."
            sleep 2
          done

      - name: Build with Maven
        env:
          SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/B2_final_touch
          SPRING_DATASOURCE_USERNAME: postgres
          SPRING_DATASOURCE_PASSWORD: jaimeislam10
        run: mvn -B package --file pom.xml

      - name: SonarCloud Scan
        uses: sonarsource/sonarqube-scan-action@master
        with:
          args: >
            -Dsonar.projectKey=mouadmakboul_B2B_PostgreSql-docker
            -Dsonar.organization=mouadmakboul
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.java.binaries=target/classes
        env:
          SONAR_TOKEN: ${{ secrets.TOKEN }}

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: java
          # If you wish to specify custom queries, you can do so here or in a config file.
          # queries: ./path/to/local/query, your-org/your-repo/queries@main

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
        with:
          category: '/language:java'
        env:
          CODEQL_WORKFLOW_PATH: .github/workflows/build.yml
